FROM paddlepaddle/paddle:2.4.2-gpu-cuda11.7-cudnn8.4-trt8.4
MAINTAINER lianshufeng <251708339@qq.com>

# 添加 依赖
Add ./ /docker


RUN apt-get update -y \
  && apt-get install libsndfile-dev libsndfile1 -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/PaddlePaddle/PaddleSpeech.git /home/PaddleSpeech  
RUN pip3 uninstall mccabe -y ; exit 0;

#安装依赖
RUN pip3 install -r /docker/requirements-gpu.txt

WORKDIR /home/PaddleSpeech/
RUN python setup.py bdist_wheel
# RUN pip install dist/*.whl -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install dist/*.whl


#缓存模型包
RUN bash /docker/script/install.sh


# 工作目录
WORKDIR /work


CMD ['bash']

